force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Event #</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LocationController.cls
public with sharing class LocationController {
    @AuraEnabled(cacheable=true)
    public static List<Location__c> getEventLocations(Id eventId) {
        
        List<Event__c> events = [Select Location__c From Event__c Where Location__c = :eventId];
        List<Id> locationIds = new List<Id>();
        for(Event__c e : events){
            locationIds.add(e.Location__c);
        }
        return [
            SELECT Id, Name, Landmark__c
            FROM Location__c
            WHERE Id = : locationIds
            WITH SECURITY_ENFORCED
        ];
    }
}